# Generated by Django 5.1.3 on 2026-05-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='پرسش')),
                ('answer_text', models.TextField(blank=True, verbose_name='پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_chunk', models.TextField(verbose_name='بخش مرتبط')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='qa.question')),
            ],
            options={
                'verbose_name': 'منبع',
                'verbose_name_plural': 'منابع',
            },
        ),
    ]
