# Generated by Django 5.1.3 on 2026-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='documents/', verbose_name='فایل')),
                ('content', models.TextField(blank=True, verbose_name='متن کامل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_indexed', models.BooleanField(default=False, verbose_name='ایندکس شده')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
            },
        ),
    ]
